name: Deploy to Server

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute remote commands
        env:
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USERNAME@$SERVER_HOST \
            "cd /path/to/your/app && \
            git pull origin main && \
            pip install -r requirements.txt && \
            python manage.py migrate && \
            systemctl restart your-service-name"
