name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to AWS
        env:
          AWS_SERVER_IP: ${{ secrets.AWS_SERVER_IP }}
          AWS_USERNAME: ${{ secrets.AWS_USERNAME }}
        run: |
          scp -r ./* ${{ env.AWS_USERNAME }}@${{ env.AWS_SERVER_IP }}:/home/ubuntu/ci-cd-practice
