name: Deploy to Server

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install expect
        run: sudo apt-get install -y expect

      - name: Execute remote commands
        env:
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          spawn ssh $SERVER_USERNAME@$SERVER_HOST
          expect "password:"
          send "$SERVER_PASSWORD\r"
          expect "$ "
          send "git pull origin main\r"
          expect "$ "
